<a href="https://colab.research.google.com/github/mostofa89/Pytorch_Fundamentals/blob/main/PytorchBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import torch
import numpy as np

#Empty Tensor

In [84]:
x = torch.empty(7)
x

tensor([-9.9824e+27,  1.3382e-42,  1.4013e-45,  0.0000e+00,  1.4013e-45,
         0.0000e+00,  1.4013e-45])

In [85]:
x = torch.empty(2, 3)
x

tensor([[3.6013e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [86]:
x = torch.empty(3, 3, 3)
x

tensor([[[-1.0217e+28,  1.3382e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

#Zeros and Ones

In [87]:
x = torch.zeros(2, 2)
x

tensor([[0., 0.],
        [0., 0.]])

In [88]:
x = torch.zeros(2, 2)
x

tensor([[0., 0.],
        [0., 0.]])

In [89]:
x = torch.ones(2, 2, dtype=torch.float64)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [90]:
x = torch.ones(2, 2, dtype=torch.int32)
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [91]:
x = torch.ones(2, 2, dtype=torch.int64)
x.dtype

torch.int64

In [92]:
x = torch.ones(2, 2, 2, dtype=torch.int64)
x.shape

torch.Size([2, 2, 2])

In [93]:
x = torch.ones(2, 2, 2, dtype=torch.int64)
x.size()

torch.Size([2, 2, 2])

#Creating Tensor using Array

In [94]:
nums = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
x = torch.tensor(nums)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
nums = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 14], [16, 17, 18]]

  ]
x = torch.tensor(nums)
print(x.shape)
print(x.ndim)
print(x.dtype)
x

torch.Size([2, 3, 3])
3
torch.int64


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 14],
         [16, 17, 18]]])

#Tensor using Using Random

In [96]:
tensor_4d = np.random.rand(4, 2, 2, 64)
x = torch.tensor(tensor_4d)

x

tensor([[[[0.9535, 0.6715, 0.4264,  ..., 0.5588, 0.3443, 0.0839],
          [0.5264, 0.8446, 0.9606,  ..., 0.0457, 0.6529, 0.7521]],

         [[0.4155, 0.2553, 0.8045,  ..., 0.8208, 0.8913, 0.3653],
          [0.3602, 0.7630, 0.5350,  ..., 0.2479, 0.4074, 0.4160]]],


        [[[0.1018, 0.7131, 0.1873,  ..., 0.3180, 0.9478, 0.8595],
          [0.3958, 0.3460, 0.8973,  ..., 0.8814, 0.7815, 0.7289]],

         [[0.7754, 0.1682, 0.3164,  ..., 0.5152, 0.4249, 0.7553],
          [0.1418, 0.4067, 0.8573,  ..., 0.7322, 0.2423, 0.0487]]],


        [[[0.9803, 0.5146, 0.6156,  ..., 0.1221, 0.1587, 0.9450],
          [0.6983, 0.4232, 0.0969,  ..., 0.3942, 0.3199, 0.8925]],

         [[0.6634, 0.7153, 0.7929,  ..., 0.2139, 0.2281, 0.9311],
          [0.1836, 0.1835, 0.9987,  ..., 0.1512, 0.6737, 0.1525]]],


        [[[0.5251, 0.8390, 0.6672,  ..., 0.5410, 0.0498, 0.8243],
          [0.8972, 0.7234, 0.5550,  ..., 0.4609, 0.8165, 0.2869]],

         [[0.3598, 0.9503, 0.8092,  ..., 0.8042, 0.6749,

In [97]:
x = torch.rand(4, 5, 2, 3)
print(x.shape[0])
print(x.shape[1])
print(x.shape[2])
print(x.shape[3])
x

4
5
2
3


tensor([[[[0.5213, 0.8691, 0.1660],
          [0.3721, 0.1702, 0.5045]],

         [[0.0654, 0.6997, 0.1598],
          [0.4236, 0.4845, 0.2378]],

         [[0.0117, 0.5235, 0.1866],
          [0.6078, 0.4050, 0.6220]],

         [[0.0450, 0.2554, 0.5788],
          [0.3618, 0.0075, 0.1124]],

         [[0.0837, 0.3861, 0.9664],
          [0.9761, 0.8178, 0.5756]]],


        [[[0.4278, 0.7559, 0.8965],
          [0.4049, 0.3612, 0.2541]],

         [[0.0396, 0.9612, 0.3034],
          [0.8927, 0.3267, 0.7575]],

         [[0.0504, 0.3816, 0.3429],
          [0.0568, 0.5323, 0.5271]],

         [[0.9939, 0.9146, 0.2517],
          [0.8160, 0.1286, 0.6287]],

         [[0.4364, 0.5693, 0.1541],
          [0.4717, 0.9479, 0.6284]]],


        [[[0.2288, 0.4095, 0.2159],
          [0.1190, 0.0684, 0.4549]],

         [[0.2121, 0.3255, 0.1973],
          [0.9642, 0.1156, 0.2816]],

         [[0.4458, 0.2696, 0.4080],
          [0.0050, 0.3840, 0.5696]],

         [[0.1724, 0.2746, 0.8500]

In [98]:
x = 10 * torch.rand(4, 8, 2, 4)
x

tensor([[[[9.2149e+00, 7.0811e+00, 2.4739e-01, 5.2094e+00],
          [8.9963e+00, 6.3051e+00, 4.9185e+00, 4.9109e+00]],

         [[4.8711e+00, 1.2135e+00, 1.3194e+00, 7.6850e+00],
          [9.0410e+00, 2.4565e+00, 2.7503e+00, 9.3230e+00]],

         [[6.7241e+00, 3.3585e+00, 5.8176e+00, 3.4832e+00],
          [1.8234e-01, 6.3716e+00, 1.0078e+00, 5.3844e+00]],

         [[9.3637e+00, 4.1816e+00, 9.2480e+00, 7.9462e+00],
          [9.3367e+00, 9.0993e+00, 4.0853e+00, 4.1277e+00]],

         [[9.9162e+00, 2.6910e+00, 5.2346e+00, 3.7239e+00],
          [4.6448e+00, 9.1686e+00, 8.3968e+00, 9.2481e+00]],

         [[9.4569e+00, 8.0264e+00, 9.0847e+00, 9.1269e+00],
          [8.7658e-01, 1.9019e+00, 5.3323e+00, 4.3023e-01]],

         [[5.2253e+00, 7.5615e+00, 1.5066e+00, 1.2971e+00],
          [8.1563e+00, 6.9254e+00, 4.8658e+00, 6.8432e+00]],

         [[1.1391e+00, 8.6775e+00, 6.7005e+00, 8.8959e+00],
          [3.1726e+00, 4.5007e-03, 7.3161e+00, 9.8150e+00]]],


        [[[5.0725e-01,

#Reshape

In [99]:
x = torch.arange(1, 11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
#  Reshaping into 2D
x = x.reshape(2, 5)
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [101]:
x = torch.arange(1, 28)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27])

In [102]:
#  Reshaping into 3D
x = x.reshape(3, 3, 3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

#Squeezing and Unsqueezing

##Unsqueezing
* Add A dimention

In [103]:
x = torch.tensor([[10, 20, 30], [40, 50, 60]])
print("Original Shape:", x.shape)

Original Shape: torch.Size([2, 3])


In [104]:
x_dim0 = x.unsqueeze(dim=0)
print("Unscreened at dim=0:", x_dim0.shape)
print(x_dim0)

Unscreened at dim=0: torch.Size([1, 2, 3])
tensor([[[10, 20, 30],
         [40, 50, 60]]])


In [105]:
x_dim1 = x.unsqueeze(dim=1)
print("Unscreened at dim=1:", x_dim1.shape)
print(x_dim1)

Unscreened at dim=1: torch.Size([2, 1, 3])
tensor([[[10, 20, 30]],

        [[40, 50, 60]]])


##Squeezing
* Remove Dimention

In [106]:
y = torch.tensor([[[10], [20], [30]]])
print("Original Shape:", y.shape)

Original Shape: torch.Size([1, 3, 1])


In [107]:
y_all = y.squeeze()
print("Squeezed all:", y_all.shape)

Squeezed all: torch.Size([3])


In [108]:
y_dim0 = y.squeeze(dim=0)
print("Squeezed dim=0:", y_dim0.shape)

Squeezed dim=0: torch.Size([3, 1])


#Arange

In [109]:
nums = torch.arange(0, 80, 10)
nums

tensor([ 0, 10, 20, 30, 40, 50, 60, 70])

In [110]:
nums = torch.arange(1, 11)
nums

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
nums = torch.arange(1, 11).reshape(5, 2)
nums

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [112]:
nums = torch.arange(1, 11).reshape(2, 5)
nums

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [113]:
nums = torch.arange(1, 10).reshape(3, 1, 3)
nums

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])

In [114]:
nums = torch.arange(1, 28).reshape(3, 3, 3)
nums

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

# Tensors Arithmetic Operations

In [115]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

tensor([[0.8983, 0.1910],
        [0.2223, 0.8720]])
tensor([[0.9374, 0.9220],
        [0.9949, 0.2361]])


##Addition

In [116]:
x += 10
x

tensor([[10.8983, 10.1910],
        [10.2223, 10.8720]])

In [117]:
z = torch.add(x, y)
z

tensor([[11.8357, 11.1130],
        [11.2172, 11.1081]])

In [118]:
x.add_(y)
print(x)

tensor([[11.8357, 11.1130],
        [11.2172, 11.1081]])


##subtraction

In [119]:
x -= 10
x

tensor([[1.8357, 1.1130],
        [1.2172, 1.1081]])

In [120]:
z = torch.sub(x, y)
z

tensor([[0.8983, 0.1910],
        [0.2223, 0.8720]])

In [121]:
x.sub_(y)
x

tensor([[0.8983, 0.1910],
        [0.2223, 0.8720]])

##Multiplication

In [122]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [123]:
x *= 10
x

tensor([10, 20, 30])

In [124]:
z = torch.mul(x, y)
z

tensor([ 40, 100, 180])

In [125]:
x.mul_(y)
x

tensor([ 40, 100, 180])

##Devission

In [126]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [127]:
y //= 2

y

tensor([2, 2, 3])

In [128]:
z = torch.div(x, y)
z

tensor([0.5000, 1.0000, 1.0000])

In [129]:
x.dtype

torch.int64

##Reminder

In [130]:
z = torch.remainder(x, y)
z

tensor([1, 0, 0])

In [131]:
x.remainder_(y)
z

tensor([1, 0, 0])

#Matrix Multiplication

*   Elementwise Multiplication
*   Matrix Multiplication / Dot Poduct



In [132]:
#1D Matrixx
num1 = torch.tensor([1, 2, 3])
num2 = torch.tensor([2, 3, 4])

In [133]:
#2D Matrix
nums1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
nums2 = torch.tensor([[1, 3, 5], [2, 4, 6]])

##Elementwise

1D Tensor

In [134]:
print(f"Elementwise Multiplication of num1 and num1 {num1 * num1}")

Elementwise Multiplication of num1 and num1 tensor([1, 4, 9])


In [135]:
print(f"Elementwise Multiplication of num1 and num2 {num1 * num2}")

Elementwise Multiplication of num1 and num2 tensor([ 2,  6, 12])


2D Tensor

In [136]:
print(f"Elementwise Multiplication of nums1 and nums1 {nums1 * nums1}")

Elementwise Multiplication of nums1 and nums1 tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [137]:
print(f"Elementwise Multiplication of nums1 and nums2 {nums1 * nums2}")

Elementwise Multiplication of nums1 and nums2 tensor([[ 1,  6, 15],
        [ 8, 20, 36]])


## Matrix Multiplication / Dot Product

In [138]:
nums2 = torch.tensor([[1, 2], [1, 3], [2, 4]])

Keep in mind that it can give shape error because mat do profuct need to satisfy the condition of (M * N) * (N * M)

In [139]:
result = torch.matmul(num1, num2)
result

tensor(20)

#Agregating Tensor

In [140]:
print("==============1D Matrix==============")
one_d_mat = torch.arange(1, 25)
print(one_d_mat)

print("==============2D Matrix==============")
one_d_mat1 = torch.arange(1, 16)
two_d_mat = one_d_mat1.reshape(5, 3)
print(two_d_mat)

print("==============3D Matrix==============")
one_d_mat_ = torch.arange(1, 22)
three_d_mat = one_d_mat_.reshape(7, 1, 3)
print(three_d_mat)

==============1D Matrix==============
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
==============2D Matrix==============
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
==============3D Matrix==============
tensor([[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]],

        [[13, 14, 15]],

        [[16, 17, 18]],

        [[19, 20, 21]]])


##Sum

In [141]:
print(f"Sum of 1D Matrix {torch.sum(one_d_mat)}")
print(f"Sum of 2D Matrix {torch.sum(two_d_mat)}")
print(f"Sum of 3D Matrix {torch.sum(three_d_mat)}")

Sum of 1D Matrix 300
Sum of 2D Matrix 120
Sum of 3D Matrix 231


##Mean


In [142]:
print(f"Mean of 1D Matrix {torch.mean(one_d_mat.float())}")
print(f"Mean of 2D Matrix {torch.mean(two_d_mat.float())}")
print(f"Mean of 3D Matrix {torch.mean(three_d_mat.float())}")

Mean of 1D Matrix 12.5
Mean of 2D Matrix 8.0
Mean of 3D Matrix 11.0


##Max and Min

In [143]:
print(f"Max Value of 1D Matrix {torch.max(one_d_mat)}")
print(f"Max Value of 2D Matrix {torch.max(two_d_mat)}")
print(f"Max Value of 3D Matrix {torch.max(three_d_mat)}")

Max Value of 1D Matrix 24
Max Value of 2D Matrix 15
Max Value of 3D Matrix 21


In [144]:
print(f"Min Value of 1D Matrix {torch.min(one_d_mat)}")
print(f"Min Value of 2D Matrix {torch.min(two_d_mat)}")
print(f"Min Value of 3D Matrix {torch.min(three_d_mat)}")

Min Value of 1D Matrix 1
Min Value of 2D Matrix 1
Min Value of 3D Matrix 1


In [145]:
print(f"TheIndex of Max Value of 1D Matrix {torch.argmax(one_d_mat)}")
print(f"TheIndex of Max Value of 2D Matrix {torch.argmax(two_d_mat)}")
print(f"TheIndex of Max Value of 3D Matrix {torch.argmax(three_d_mat)}")

TheIndex of Max Value of 1D Matrix 23
TheIndex of Max Value of 2D Matrix 14
TheIndex of Max Value of 3D Matrix 20


In [146]:
print(f"TheIndex of Min Value of 1D Matrix {torch.argmin(one_d_mat)}")
print(f"TheIndex of Min Value of 2D Matrix {torch.argmin(two_d_mat)}")
print(f"TheIndex of Min Value of 3D Matrix {torch.argmin(three_d_mat)}")

TheIndex of Min Value of 1D Matrix 0
TheIndex of Min Value of 2D Matrix 0
TheIndex of Min Value of 3D Matrix 0


#Slicing

##1D

In [147]:
x = 10 * torch.rand(4)
print(x)

tensor([0.3094, 3.8160, 3.0814, 2.7979])


In [148]:
print(x[0 : len(x) - 1])

tensor([0.3094, 3.8160, 3.0814])


In [149]:
print(x[2 : len(x) - 1])

tensor([3.0814])


In [150]:
# Step size 2
print(x[::2])

tensor([0.3094, 3.0814])


In [151]:
print(x[3 : len(x) - 1])

tensor([])


In [152]:
#Negative Index
print(x[-3 : ])

tensor([3.8160, 3.0814, 2.7979])


##2D

In [153]:
x = 10 * torch.rand(4, 4)
print(x)

tensor([[7.2786, 2.5367, 5.3887, 8.6545],
        [0.4431, 0.1035, 5.8021, 9.0304],
        [1.5626, 2.6152, 5.6292, 2.2827],
        [6.3149, 6.0569, 2.4631, 2.9401]])


In [154]:
# Row fix , column indexing
print(x[3, 0 : 3])

tensor([6.3149, 6.0569, 2.4631])


In [155]:
print(x[1, :])

tensor([0.4431, 0.1035, 5.8021, 9.0304])


In [156]:
#Column fix and row slicing
print(x[0 : 2, 3])

tensor([8.6545, 9.0304])


In [157]:
# slcing both at the same time
print(x[0 : 2, 0 : 3])

tensor([[7.2786, 2.5367, 5.3887],
        [0.4431, 0.1035, 5.8021]])


In [158]:
print(x[ : , 1])

tensor([2.5367, 0.1035, 2.6152, 6.0569])


##3D

In [159]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
z = torch.tensor([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

print(x)
print(y)
print(z)
print("=============3D Tensor=============")
nums = torch.stack([x, y, z])
nums

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
=============3D Tensor=============


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 1,  3,  5],
         [ 7,  9, 11],
         [13, 15, 17]],

        [[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]])

In [160]:
#Slicing in Z-axis
print(nums[1, 2, 0:2])

tensor([13, 15])


In [161]:
#Slicing in Y-axis
print(nums[1, 0 : 2, 2])

tensor([ 5, 11])


In [162]:
#Slicing in z-axis
print(nums[0 : 2, 2, 2])

tensor([ 9, 17])


In [163]:
#Slicing in every axis
print(nums[0 : 2, 0 : 2, 0 : 2])

tensor([[[1, 2],
         [4, 5]],

        [[1, 3],
         [7, 9]]])


# Indexing

In [ ]:
#Indexing in 3D Tensor accessing column 0 of the first matrix
nums[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Indexing in 3D Tensor accessing column 1 of the matrix
nums[1]

tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]])

In [ ]:
#Indexing in 3D Tensor accessing row 1, column 1 of the matrix
nums[1, 1]

tensor([ 7,  9, 11])

In [ ]:
#Accessing specific Element in 3D Tensor
print(nums[0, 0, 0])

tensor(1)


In [169]:
#Accessing specific Element in 3D Tensor
print(nums[2, 2, 2])

tensor(18)
